config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :types, only: [:index, :show]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/profile', to: 'pages#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
require 'csv'

class Organization < ApplicationRecord
  # has_one :admin
  acts_as_taggable_on :types
  has_and_belongs_to_many :users
  has_many :projects
  validates :name, presence: true
  validates :email, presence: true

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Name", "Email", "Projects: Positions", "Users"]

      all.each do |organization|
        projects = nil
        users = nil
        row = [organization.name, organization.email]
        # if organization.users.any?
        #   users = organization.users.collect{|u| "#{u.first_name} #{u.email}"}.join(", ")
        #   row << users
        # end
        if organization.projects.any?
          all_projects = organization.projects
          projects = []
          all_projects.each do |project|
            projects.append("#{project.title}: [#{project.positions.collect { |p| p.title }.join(", ")}]  ")
          end
          projects = projects.join(", ")
        end
        csv << [organization.name, organization.email, projects]
      end
    end
  end
end

app/models/position.rb
class Position < ApplicationRecord
  acts_as_taggable_on :skills
  belongs_to :project
  validates :title, length: { in: 3..20 }
  validates :project_id, presence: true
  validates :user_id, presence: true
  validates :integer, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_taggable_on :skills
  has_many :positions
  belongs_to :organization
  validates :title, length: { in: 3..20 }
  validates :organization_id, presence: true
end

app/models/university.rb
class University < ApplicationRecord
    has_many :organizations
    has_many :users
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_taggable_on :skills, :interests
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  has_and_belongs_to_many :organizations
  belongs_to :universities
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html
      format.csv { send_data @organizations.to_csv, filename: "organizations-#{Date.today}.csv" }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :email, :type_list)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def profile
        render :layout => false
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
    def index
      @tags = ActsAsTaggableOn::Tag.all
    end
  
    def show
      @type =  ActsAsTaggableOn::Tag.find(params[:id])
      @organizations = Organization.tagged_with(@type.name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, type_path(tag)%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><em>Project Matching</em> - An Open Source project by DSC UMass x NTU. </small>
  <nav>
    <ul>
      <li><%= link_to "Our GitHub", 'https://github.com/dsc-umass/project-matching' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Project Matching", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Organizations", organizations_path %></li>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Profile', profile_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectMatching</title>
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield :top_content %>
    <div class="container">
        <h1><%= yield :header %></h1>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :Type %>
    <%= form.text_field :type_list, value: form.object.type_list.to_s %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<h4><%= organization.name %></h4>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.email %></td>
        <td><%= render organization.types %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
<strong>Tags:</strong>
<%= render @organization.types %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="center jumbotron">
      <h1>Welcome!</h1>
      <h2>Ready to find awesome projects?</h2>
      <p>
        <%= link_to 'Sign up now!', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
      </p>
  </div>
<% end %>

app/views/pages/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectMatching</title>
    <%= render 'layouts/rails_default' %>
  </head>
  <body id="profile-page">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <div class="container">
        <div class = "container">
            <div class = "container" id = "profile-card">
                <form>
                  <div class = "form-row text-center">
                    <div class = "col-12">
                        <svg class="text-center btn btn-primary" id = "profile-pic" width="8em" height="8em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="gray" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for = "first-name">First Name</label>
                      <input type="text" class="form-control">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="last-name">Last Name</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="institution">Institution</label>
                    <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-md-12">
                    <label for="headline">Headline</label>
                    <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-md-12">
                    <label for="bio">Bio</label>
                    <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-md-12">
                    <label for="github">GitHub</label>
                    <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-md-12">
                    <label for="linkedin">LinkedIn Profile URL</label>
                    <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-md-12" style="margin-bottom: 10rem">
                    <label for="website">Website</label>
                    <input type="text" class="form-control">
                  </div>
                  <div>
                      <h2>Your best skills</h2>
                      <h2>Your other skills</h2>
                  </div>
                  <div class = "form-row text-center">
                    <div class = "col-12">
                      <button type="submit" class="text-center btn btn-primary" id="resume-upload-btn">Click to Upload your Resume</button>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary" id="profile-submit-btn">Submit</button>
                </form>
            </div>
        </div>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @organizations %></div>

app/views/types/index.html.erb
<%= render @types %>

app/views/types/show.html.erb
<h1><%= @type.name %></h1>
<div><%= render @organizations %></div>